name: Snake

on:
  workflow_dispatch:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

jobs:
  mksnake:
    name: Generate snake.svg
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate the snake.svg file
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: xfn14
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
      
      - name: Push file to branch output
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}